### ISSUE TITLE
Hello! Some suggestions for you

### ISSUE THREAD

**Issue by Helias** [wobgob/azerothcore-wotlk#54]
I appreciated a lot that you are open-sourcing your server based on azerothcore, anyone should do it.
I have some suggestions for you:

1) I see that you are keeping some modules inside azerothcore-wotlk, you could use git submodule https://git-scm.com/book/it/v2/Git-Tools-Submodules
In this way, you will keep the sources and the updates in separate repositories but you'll keep only a simple reference in your main core repository (see mod-eluna-lua-engine and the directory LuaEngine for example)

2) Any modules or tools of yours can be present in the AzerothCore catalogue https://www.azerothcore.org/catalogue.html#/home
You only need to add the GitHub topic "azerothcore-tools" in the tool repository and "azerothcore-module" for the module repository.

To change a github topic you have to modify the settings in top-right, here is an example:

![image](https://user-images.githubusercontent.com/519778/159096451-c4caaa27-077f-4f0f-b194-7ecab5d40374.png)

**NOTE: after that you add the github topic use the incognito browser or clear the localStorage/cache of your browser to see your modules in the catalogue**

**Comment by Helias** [comment]
Additionally, may this can be helpful https://github.com/benjymansy123/mod-worgoblin
I don't know if you want to add some custom "patch-Z", you could add the goblin or worgen races if you want.

Unfortunately this "module" that I linked is more a patch than a module, would be nice to convert it into a real AC module, meanwhile you could try and test it.

**Comment by jarrodjeffi** [comment]
Thanks for the kind words. The reason I use a monolithic repository is because it's easier to maintain and most of my modules are custom made for the server and can't just be ripped out and used anywhere because of a range of dependencies like custom items. I'll think about making "clean" versions of my modules to provide to the AzerothCore community.

**Comment by Helias** [comment]
Ok, but keep in mind that for a good long-term solution it is better to keep the customization in the modules and do not change the core of your mono-repository, otherwise you'll start to have some conflicts with master AC.

Anyways, I hope all the best for this project, hope it'll grow up! 👍,
